# Generated by Django 4.0.1 on 2022-01-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoginsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidmodel')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loginsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='cidmodel',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loginsmodel'),
        ),
    ]
