# Generated by Django 4.0.1 on 2022-01-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cidmodel_name_urlsmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlsmodel',
            name='cid',
        ),
    ]
